# Generated by Django 6.0 on 2025-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_app", "0002_remove_video_thumbnail_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
